[package]
name = "ade_key_extractor"
description = "ADE key extractor for DeDRM"
readme = "README.md"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
categories = []
keywords = ["adobe", "keyextractor"]
include = ["**/*.rs", "Cargo.toml"]

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
clap = { version = "4.5", features = ["derive", "wrap_help", "env"] }
log = "0.4.25"
colored = "2.2.0"
flexi_logger = "0.29"
libade_extract_key = { path = "../lib" }

[[bin]]
name = "ade-extract-key"
path = "src/main.rs"

[lints]
workspace = true
